language: csharp
mono: none
dotnet: 2.0.0
script:
 - dotnet restore
 - dotnet build --configuration Release
deploy:
 provider: azure_web_apps
 username: $AzureEmail
 password: $AzurePassword
 site: CITestAPI